evoactivity/ember-svg-jar

app/helpers/svg-jar.js
+ Provide `svgJar` helper method outside of templates (i.e. in routes, components, controllers)
+ Attempts to resolve #14
=> Make svgJar a callable method

src/index.js
Recent versions of ember-cli emit deprecations warnings like:
```
DEPRECATION: Ember CLI addons manage their own module transpilation during the `treeForAddon` processing. `ember-svg-jar` (found at `XXX/node_modules/ember-svg-jar`) has overridden the `this.options.ember-cli-babel.compileModules` value which conflicts with the addons ability to transpile its `addon/` files properly.
```
This is happening because ember-cli now has a standard use for an addon's `this.options`, which is colliding with ember-svg-jar's own usage.
This pr just renames `this.options` to `this.svgJarOptions` to avoid the problem.
=> Avoid options collision deprecations

docs/configuration.md, node-tests/acceptance/viewer-builder-test.js, package.json, public/index.html, src/index.js, src/viewer-builder.js, symbols-loader.html
It's useful in development mode, if you use custom `rootURL` in `config/environment.js`.
By default, the SVGJar viewer is available at `http://localhost:4200/ember-svg-jar/index.html`. If you set `rootURL` to `/myapp/`, the viewer URL will change to `http://localhost:4200/myapp/ember-svg-jar/index.html`.
Fixes #22 and #25.
=> Add rootURL option

addon/utils/make-svg.js, app/helpers/svg-jar.js, node-tests/acceptance/inline-packer-test.js, src/index.js, src/inline-packer.js, tests/unit/utils/make-svg-test.js
This change allows ember-svg-jar to be used by addons. [Recent work](https://github.com/ivanvotti/ember-svg-jar/issues/29) also mentioned making it work in addons, but that only makes it work within an addon's own dummy app, when consumed as a `devDependency`.
This change makes ember-svg-jar work as a `dependency`. Multiple addons and/or the top-level app can all use it simultaneously without stomping each other (with the one caveat that the namespace of SVG asset ids is flat, so `{{svg-jar "something"}}` has a consistent meaning no matter where it appears, so if multiple addons try to use the same id, it's undefined which wins.
I only implemented this for the default, inline strategy. It would be possible in the future to do for the symbol strategy.
=> Better addon support

addon/utils/make-svg.js
There are a ton of deprecations thrown from Ember.Logger now. `console.warn` is supported back to IE 8, so I think this should be fine 👍
=> Use console.warn instead of Ember.Logger

addon/utils/make-svg.js, tests/unit/utils/make-svg-test.js
=> Warn when assetName is `undefined` or `null` instead of throwing error

addon/utils/make-svg.js, package.json, yarn.lock
See https://github.com/emberjs/rfcs/pull/322
=> Switch to ember-copy

addon/utils/make-svg.js, package.json, yarn.lock
AFAICT `asset.attrs` is a shallow object and does not implement the [`Copyable` interface][1] or the `copy` method. Calling the `copy` function from ember-copy on it therefore only creates a shallow copy.
This is exactly what [`assign`][2] does, when you assign into an empty object.
Referencing #77.
[1]: https://www.emberjs.com/api/ember/release/classes/Ember.Copyable
[2]: https://emberjs.com/api/api/ember/release/functions/@ember%2Fpolyfills/assign
=> refactor(make-svg): replace ember-copy with assign

README.md
This PR documents how to use this addon from within another addon (such as a UI components library).
As a `devDependency`, you get an error that there is a missing inline svg.
Related to https://github.com/ivanvotti/ember-svg-jar/pull/52
P.S. thanks for your work on this addon. It is a huge help to my work!
=> README - Document usage in an addon

package.json
`husky`, `lint-staged` and `prettier` are not needed by users of this addon and are only needed when developing this addon so they should be in the `devDependencies` section.
=> package.json: Move development dependencies into `devDependencies`

docs/configuration.md, lib/build-options.js, lib/validate-assets.js, node-tests/unit/build-options-test.js
We would like our build to fail on CI when an SVG without a `viewBox` is submitted. This new option allows us to throw an error instead of printing the console warning.
/cc @ivanvotti
=> Add `validations.throwOnFailure` option

README.md, addon/utils/make-svg.js, tests/integration/helpers/svg-jar-test.js, tests/unit/utils/make-svg-test.js
Add `title` and `desc` elements to SVGs if these properties are passed to `svg-jar`. The `aria-labelledby` attribute will be added and point to either or both of these elements if they are passed in. This approach also accepts translations.
Fixes #43
=> Add accessibility options

package.json, yarn.lock
We're not targeting any versions of Ember that require this
=> Remove ember-assign-polyfill

addon/components/svg/index.hbs, addon/components/svg/index.js, app/components/svg.js, ember-cli-build.js, lib/build-options.js, lib/default-gens.js, lib/hbs-packer.js, lib/index.js, lib/inline-packer.js, lib/utils.js, lib/validate-options.js, node-tests/unit/build-options-test.js
This PR depends on #185, its the actual hbs strategy implementation from #166
=> Hbs strategy

.github/workflows/test.yml, config/ember-try.js, ember-cli-build.js, package.json, yarn.lock
Adds two new scenarios for ember-try: embroider-safe and embroider-optimized. Embroider-safe does not enable any tree shaking optimizations where as embroider-optimized enables them all.
=> Add @embroider/test-setup to ember-try scenarios

addon/utils/make-svg.js
See https://deprecations.emberjs.com/v4.x/#toc_ember-polyfills-deprecate-assign
=> Migrate from Ember.assign to Object.assign for ember-4.0 compatibility

packages/ember-svg-jar/lib/symbolizer/refs-extractor.js, packages/ember-svg-jar/lib/symbolizer/symbol-filter.js, packages/ember-svg-jar/lib/utils.js, packages/ember-svg-jar/package.json, yarn.lock
Upgraded cheerio to latest to resolve ReDos security vulnerability introduced by nth-check@1.0.2.
Vulnerability details can be found [here](https://security.snyk.io/vuln/SNYK-JS-NTHCHECK-1586032)
The dependency chain that introduced this issue is as follows: `ember-svg-jar@2.3.4 > cheerio@0.22.0 > css-select@1.2.0 > nth-check@1.0.2`
The latest version Cheerio no longer requires `css-select`.
**Note:** I ran `yarn-deduplicate` ([package](https://github.com/scinos/yarn-deduplicate)) to clean up the yarn lock file since the project is running `yarn v1`, this is why there are a few more changes in the yarn-lock files than normal.
=> Fix: Upgrade Cheerio to patch security vulnerability

packages/ember-svg-jar/package.json, packages/ember-svg-jar/types/glint.d.ts, packages/ember-svg-jar/types/helpers/svg-jar.d.ts, yarn.lock
This commit adds two files that can be read by Ember apps using glint so that they can benefit from glint's type-checking.
I think I have included all of the possible named attributes that can get passed to the `{{svg-jar}}` helper.
To wit:
```ts
interface SvgJarAttrs {
width?: string;
height?: string;
class?: string;
role?: string;
title?: string;
desc?: string;
}
```
=> feat: Add typing for glint

packages/ember-svg-jar/addon/utils/make-svg.js, packages/ember-svg-jar/tests/integration/helpers/svg-jar-test.js
The current implementation uses `guidFor` this will cache ids and reuse them if the same value is passed to `guidFor`, see https://github.com/emberjs/ember.js/blob/4e3300bdfe75da14f9714b6b1539dbd1612c5af2/packages/%40ember/-internals/utils/lib/guid.ts#L97
The ids in a HTML document should be unique. However if a `title` or `desc` is reused, for example you have a recurring element, then `svg-jar` generates ids which match for the recurring element.
This commit uses the `uniqueId` function from the `unique-id` helper to generate a unique id regardless of the `svg-jar` `title` or `desc` matching previous `svg-jar`.
Unfortunately `uniqueId` is not exported so it is copy and pasted. In the future it will be possible to import it, see https://github.com/emberjs/ember.js/issues/20165
Fixes …
=> Use `uniqueId` for recurring `title` and `desc`

packages/ember-svg-jar/addon/helpers/svg-jar.js, packages/ember-svg-jar/lib/inline-packer.js, packages/ember-svg-jar/node-tests/acceptance/inline-packer-test.js
=> update inline strategy

packages/ember-svg-jar/lib/index.js, packages/ember-svg-jar/lib/utils.js
Ember CLI requires every addon's `index.js` file when running any command.
I noticed that requiring `ember-svg-jar`'s `index.js` file takes a bit of time.
This PR should speed things up a bit by only requiring some packages when they are actually used.
Before: 170-180ms
After: 25-30ms
Tested on an Apple M1 Pro MacBook using:
```js
console.time('require');
require('./index.js');
console.timeEnd('require');
```
=> Speed up requiring `index.js` file

packages/ember-svg-jar/public/index.html
Using ember-svg-jar with custom rootURL in Embroider app, throws the below mentioned error and the chunk js and css are missing from final build.
```
Building into /private/var/folders/qt/rbrkt7wx48vggvxs2tcnzy70zb1g2b/T/embroider/270ee5
Environment: development
⠏ building... [@embroider/webpack]warning: in ./ember-svg-jar/index.html <script src="customrooturl/ember-svg-jar/static/js/2.ced0fc45.chunk.js"> does not exist on disk. If this is intentional, use a data-embroider-ignore attribute.
warning: in ./ember-svg-jar/index.html <script src="customrooturl/ember-svg-jar/static/js/main.0e7a56b1.chunk.js"> does not exist on disk. If this is intentional, use a data-embroider-ignore attribute.
warning: in ./ember-svg-jar/index.html  <link rel="stylesheet" …
```
=> Fix file missing error on embroider when using custom rootURL

packages/ember-svg-jar/addon/types.ts
When using `{{svg-jar}}` helper, optional named arguments need to be `null` (so they can be filtered out in via `isNone` in https://github.com/ghedamat/ember-svg-jar/blob/v2.4.6/packages/ember-svg-jar/addon/utils/make-svg.js#L107).
If argument value is `undefined`, it gets added to DOM, which may cause issues with arguments like `width` and `height`.
This PR fixes types to add `null` as allowed arg type.
=> Allow null as arguments type

.github/workflows/ci-bsvg.yml, packages/ember-svg-jar/lib/symbolizer/refs-extractor.js, packages/ember-svg-jar/lib/symbolizer/symbol-filter.js, packages/ember-svg-jar/lib/utils.js, packages/ember-svg-jar/package.json, yarn.lock
I had a problem build my ember app because of breaking changes between cheerio 1.0.0-rc.12 and 1.0.0 final.
I guess that `"cheerio": "^1.0.0-rc.12"` tells pnpm to download 1.0.0.
I don't know exactly what I'm doing in this PR, but the thing is that tests are green.
=> upgrade cheerio to 1.0 (fixes build)

packages/ember-svg-jar/addon/utils/make-svg.js, packages/ember-svg-jar/tests/unit/utils/make-svg-test.js
Currently, it renders as
```
data-my-attribute="foo"aria-labelledby="e318f545-6c68-44f5-9b03-8805ce9ed73a"
```
which produces invalid html
=> Ensure whitespace between aria-labelledby attribute
