src/index.js
=> Add overwrite flag to MergeTrees

src/viewer-assets-builder.js
=> Fix calculating optimizedSvg file size

package.json, src/index.js, src/inline-packer.js, src/utils.js, src/viewer-assets-builder.js, src/viewer-builder.js
=> Add Windows support

addon/utils/make-svg.js, app/helpers/svg-jar.js
Fixes up some deprecation warnings.
=> fix deprecations

docs/configuration.md, lib/build-options.js, lib/index.js, node-tests/.eslintrc.js, node-tests/acceptance/inline-packer-test.js, node-tests/acceptance/viewer-assets-builder-test.js, node-tests/acceptance/viewer-builder-test.js, node-tests/runner.js, node-tests/unit/build-options-test.js, package.json, yarn.lock
Fixes #51 
Type: `Object`  
Default:
```javascript
{
style: 'position: absolute; width: 0; height: 0;',
width: '0',
height: '0',
version: '1.1',
xmlns: 'http://www.w3.org/2000/svg',
'xmlns:xlink': 'http://www.w3.org/1999/xlink'
}
```
It sets attributes for the symbols container. By default it should make the container invisible for most browsers and the result could look like this:
```handlebars
<svg style="position: absolute; width: 0; height: 0;" width="0" height="0" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<symbol id="icon-foo" viewBox="0 0 16 16"><path d=""/></symbol>
<symbol id="icon-bar" viewBox="0 0 24 24"><path d=""/></symbol>
</svg>
```
By setting `containerAttrs` you will lose all the default container attributes.
To preserve …
=> Add containerAttrs option for symbol strategy

lib/index.js
=> Ensure POSIX path in symbols loader

CONTRIBUTING.md, README.md
The table of content was generated with https://github.com/jonschlinkert/markdown-toc
=> Move contribution guide to CONTRIBUTING.md and add a Table of Contents

.travis.yml, config/ember-try.js, ember-cli-build.js
adding tests for embroider
https://github.com/embroider-build/embroider
=> Adding embroider tests

ember-cli-build.js
https://github.com/embroider-build/embroider#options
=> Enable Embroider all compat options. 

addon/utils/make-svg.js
=> Update htmlSafe import

.github/workflows/test.yml, package.json, yarn.lock
This also future-proofs us a bit when we eventually run updaters for
Ember.
=> Tweaks to Github Workflow

addon/utils/make-svg.js, config/ember-try.js, package.json, tests/acceptance/inline-svg-test.js, tests/dummy/app/templates/application.hbs, tests/fastboot/inline-svg-test.js, yarn.lock
This is built on top of #183.
Split into two separate PRs as I'm puzzled why this fails in CI
=> Add fastboot tests to help avoid issues like #178

.editorconfig, .eslintrc.js, .github/workflows/test.yml, .template-lintrc.js, README.md, config/ember-try.js, eslint-rules.js, package.json, testem.js, tests/dummy/app/app.js, tests/dummy/app/router.js, tests/dummy/app/templates/application.hbs, tests/dummy/config/ember-cli-update.json, tests/dummy/config/optional-features.json, tests/dummy/config/targets.js, tests/test-helper.js, yarn.lock
These are the updated deps needed for #186, splitted  as requested here  #166
=> deps bump for hbs strategy

lib/console-ui.js
Closes #168 (supersedes after lack of response).
=> Keep validation warnings on stderr

addon/components/svg/index.hbs, addon/components/svg/index.js, lib/hbs-packer.js
While working on readme updates I noticed some accesibility missing for the hbs strategy.. here is a follow-up PR.
=> adds more accesibility

addon/components/svg/index.hbs, addon/components/svg/index.js, lib/hbs-packer.js
Reverts ivanvotti/ember-svg-jar#188
=> Revert "adds more accesibility"

lib/index.js, lib/prepare-symbol-loader-script.js, node-tests/unit/prepare-symbol-loader-scripts-test.js, symbols-loader.html, tests/acceptance/symbols-loader-test.js, tests/integration/helpers/svg-jar-test.js
This pull request supersedes #65. Big ups to @kiwiupover for the original work.
=> Symbol placement for tests

packages/ember-svg-jar/package.json
Fixed https://github.com/ghedamat/ember-svg-jar/issues/257
=> Update types location in package.json

README.md
=> Add helper types and imports documentation

README.md
Fixes the link to fingerprinting docs
=> Fix link to fingerprinting docs
